# Generated by Django 4.2.7 on 2023-12-04 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todolist_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPerDay',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist_app.basetask')),
                ('due_date', models.DateField(default=todolist_app.models.today)),
            ],
            options={
                'verbose_name': 'Задача на день',
                'verbose_name_plural': 'Задачи на день',
            },
            bases=('todolist_app.basetask',),
        ),
        migrations.CreateModel(
            name='TaskPerMinutes',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist_app.basetask')),
                ('due_date', models.TimeField(default=datetime.time(17, 4, 43, 974391))),
            ],
            bases=('todolist_app.basetask',),
        ),
        migrations.CreateModel(
            name='TaskPerMonth',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist_app.basetask')),
                ('due_date', models.DateField(default=todolist_app.models.end_of_month)),
            ],
            options={
                'verbose_name': 'Задача на месяц',
                'verbose_name_plural': 'Задачи на месяц',
            },
            bases=('todolist_app.basetask',),
        ),
        migrations.CreateModel(
            name='TaskPerWeek',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist_app.basetask')),
                ('due_date', models.DateField(default=todolist_app.models.end_of_week)),
            ],
            options={
                'verbose_name': 'Задача на неделю',
                'verbose_name_plural': 'Задачи на неделю',
            },
            bases=('todolist_app.basetask',),
        ),
        migrations.CreateModel(
            name='TaskPerYear',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist_app.basetask')),
                ('due_date', models.DateField(default=datetime.date(2023, 12, 31))),
            ],
            options={
                'verbose_name': 'Задача на год',
                'verbose_name_plural': 'Задачи на год',
            },
            bases=('todolist_app.basetask',),
        ),
    ]
